version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "weather-data-collector"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10m10nasyur0c"
s3_prefix = "weather-data-collector"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "WeatherApiKey=\"b942d5ca038846adad450241212102\" GlueEtlScriptS3Path=\"s3://my-demo-glue-scripts/etl_raw_weather_data_cleaner.py\""
